import datetime
import inspect
from enum import Enum, IntEnum

from discord import PrivateChannel, Role, User, Message, Server, Channel, Member

from applebot.command import Command
from applebot.exceptions import BlockCommandError


class EVENTTYPE(IntEnum):
    NONE = 0  # Not actually an event
    IN = 1  # Incoming
    REQ = 2  # Request
    RESP = 3  # Response
    COM = 4  # Command
    HTTP_START = 5
    HTTP_END = 6
    OTHER = 7  # Other
    HTTP_METHOD = 8  # Method names for hooking discord.Client.http


class EventEnum(object):
    def __init__(self, event_type, params):
        self.type = [t for t in EVENTTYPE][event_type]
        self.params = params


class EventEnumBase(Enum):
    def __new__(cls, event_type, params):
        obj = object.__new__(cls)
        obj._value_ = EventEnum(event_type, params)
        return obj

    @classmethod
    def iter(cls, event_type):
        for event in cls:
            if event.value.type == event_type:
                yield event


class EVENT(EventEnumBase):
    ready = (1, {})
    resumed = (1, {})
    message = (1, {'message': Message})
    message_delete = (1, {'message': Message})
    message_edit = (1, {'before': Message, 'after': Message})
    typing = (1, {'channe': (Channel, PrivateChannel), 'user': User, 'when': datetime.datetime})
    channel_create = (1, {'channel': (Channel, PrivateChannel)})
    channel_delete = (1, {'channel': (Channel, PrivateChannel)})
    channel_update = (1, {'before': (Channel, PrivateChannel), 'after': (Channel, PrivateChannel)})
    member_create = (1, {'member': Member})
    member_delete = (1, {'member': Member})
    member_update = (1, {'before': Member, 'after': Member})
    member_ban = (1, {'member': Member})
    member_unban = (1, {'server': Server, 'user': User})
    group_join = (1, {'channel': (Channel, PrivateChannel), 'user': User})
    group_remove = (1, {'channel': (Channel, PrivateChannel), 'user': User})
    server_join = (1, {'server': Server})
    server_remove = (1, {'server': Server})
    server_update = (1, {'before': Server, 'after': Server})
    server_available = (1, {'server': Server})
    server_unavailable = (1, {'server': Server})
    server_role_create = (1, {'role': Role})
    server_role_delete = (1, {'role': Role})
    server_role_update = (1, {'before': Role, 'after': Role})
    server_emojis_update = (1, {'before': object, 'after': object})  # discord.Emoji???
    voice_state_update = (1, {'before': Member, 'after': Member})
    socket_raw_receive = (1, {'args': tuple, 'kwargs': dict})  # Variadic parameters
    socket_raw_send = (1, {'args': tuple, 'kwargs': dict})  # Variadic parameters

    # Meh... Not sure if I should finish this list...
    # req_start_private_message = (2, {'user': User})
    # req_send_message = (2, {'destination': (Channel, PrivateChannel, Server, User), 'content': str, '*': None, 'tts': bool})
    # req_send_typing = (2, {'destination': (Channel, PrivateChannel, Server, User)})
    # req_send_file = (2, {'destination': (Channel, PrivateChannel, Server, User), 'fp': (str, open), '*': None, 'filename': str, 'content': str, 'tts': bool})
    # req_delete_message = (2, {'message': Message})
    # req_delete_messages = (2, {'messages': (list, tuple)})
    # req_purge_from = (2, {'channel': Channel, '*': None, 'limit': int, 'check': FunctionType, 'before': (Message, datetime.datetime), 'after': (Message, datetime.datetime)})
    # req_edit_message = (2, {'message': Message, 'new_content': str})
    # req_get_message = (2, {'channel': (Channel, PrivateChannel), 'id': str})
    # req_pin_message = (2, {'message': Message})
    # req_unpin_message = (2, {'message': Message})
    # req_pings_from = (2, {'channel': (Channel, PrivateChannel)})
    # req_logs_from = (2, {'channel': (Channel, PrivateChannel), 'limit': int, '*': None, 'before': (Message, datetime.datetime), 'after': (Message, datetime.datetime)})
    # req_request_offline_members = (2, {'server': (Server, list, tuple)})
    # req_kick = (2, {'member': Member})
    # req_ban = (2, {'member': Member, 'delete_message_days': int})
    # req_unban = (2, {'server': Server, 'user': User})
    # req_server_voice_state = (2, {'member': Member, '*': None, 'mute': bool, 'deafen': bool})
    # req_edit_profile = (2, {'password': str, 'new_password': str, 'email': str, 'username': str, 'avatar': bytes})

    start_private_message_request = (2, {'args': tuple, 'kwargs': dict})
    send_message_request = (2, {'args': tuple, 'kwargs': dict})
    send_typing_request = (2, {'args': tuple, 'kwargs': dict})
    send_file_request = (2, {'args': tuple, 'kwargs': dict})
    delete_message_request = (2, {'args': tuple, 'kwargs': dict})
    delete_messages_request = (2, {'args': tuple, 'kwargs': dict})
    purge_from_request = (2, {'args': tuple, 'kwargs': dict})
    edit_message_request = (2, {'args': tuple, 'kwargs': dict})
    get_message_request = (2, {'args': tuple, 'kwargs': dict})
    pin_message_request = (2, {'args': tuple, 'kwargs': dict})
    unpin_message_request = (2, {'args': tuple, 'kwargs': dict})
    pins_from_request = (2, {'args': tuple, 'kwargs': dict})
    request_offline_members_request = (2, {'args': tuple, 'kwargs': dict})
    kick_request = (2, {'args': tuple, 'kwargs': dict})
    ban_request = (2, {'args': tuple, 'kwargs': dict})
    unban_request = (2, {'args': tuple, 'kwargs': dict})
    server_voice_state_request = (2, {'args': tuple, 'kwargs': dict})
    edit_profile_request = (2, {'args': tuple, 'kwargs': dict})
    change_status_request = (2, {'args': tuple, 'kwargs': dict})
    change_nickname_request = (2, {'args': tuple, 'kwargs': dict})
    edit_channel_request = (2, {'args': tuple, 'kwargs': dict})
    move_channel_request = (2, {'args': tuple, 'kwargs': dict})
    create_channel_request = (2, {'args': tuple, 'kwargs': dict})
    delete_channel_request = (2, {'args': tuple, 'kwargs': dict})
    leave_server_request = (2, {'args': tuple, 'kwargs': dict})
    delete_server_request = (2, {'args': tuple, 'kwargs': dict})
    create_server_request = (2, {'args': tuple, 'kwargs': dict})
    edit_server_request = (2, {'args': tuple, 'kwargs': dict})
    get_bans_request = (2, {'args': tuple, 'kwargs': dict})
    prune_members_request = (2, {'args': tuple, 'kwargs': dict})
    estimate_pruned_members_request = (2, {'args': tuple, 'kwargs': dict})
    create_invite_request = (2, {'args': tuple, 'kwargs': dict})
    get_invite_request = (2, {'args': tuple, 'kwargs': dict})
    invites_from_request = (2, {'args': tuple, 'kwargs': dict})
    accept_invite_request = (2, {'args': tuple, 'kwargs': dict})
    delete_invite_request = (2, {'args': tuple, 'kwargs': dict})
    move_role_request = (2, {'args': tuple, 'kwargs': dict})
    edit_role_request = (2, {'args': tuple, 'kwargs': dict})
    delete_role_request = (2, {'args': tuple, 'kwargs': dict})
    add_roles_request = (2, {'args': tuple, 'kwargs': dict})
    remove_roles_request = (2, {'args': tuple, 'kwargs': dict})
    replace_roles_request = (2, {'args': tuple, 'kwargs': dict})
    create_role_request = (2, {'args': tuple, 'kwargs': dict})
    edit_channel_permissions_request = (2, {'args': tuple, 'kwargs': dict})
    delete_channel_permissions_request = (2, {'args': tuple, 'kwargs': dict})
    move_member_request = (2, {'args': tuple, 'kwargs': dict})
    join_voice_channel_request = (2, {'args': tuple, 'kwargs': dict})

    # Not all responses will necessarily return data.
    # All responses are called as response(result: object, args: tuple, kwargs: dict), though result may be None
    start_private_message_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    send_message_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    send_typing_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    send_file_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    delete_message_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    delete_messages_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    purge_from_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    edit_message_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    get_message_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    pin_message_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    unpin_message_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    pins_from_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    request_offline_members_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    kick_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    ban_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    unban_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    server_voice_state_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    edit_profile_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    change_status_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    change_nickname_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    edit_channel_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    move_channel_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    create_channel_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    delete_channel_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    leave_server_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    delete_server_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    create_server_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    edit_server_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    get_bans_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    prune_members_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    estimate_pruned_members_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    create_invite_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    get_invite_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    invites_from_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    accept_invite_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    delete_invite_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    move_role_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    edit_role_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    delete_role_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    add_roles_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    remove_roles_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    replace_roles_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    create_role_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    edit_channel_permissions_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    delete_channel_permissions_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    move_member_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})
    join_voice_channel_response = (3, {'result': (object, None), 'args': tuple, 'kwarg': dict})

    command_received = (4, {'command': Command, 'message': Message})
    command_finished = (4, {'command': Command, 'message': Message})
    command_notfound = (4, {'command': Command, 'message': Message})
    command_blocked = (4, {'command': Command, 'error': BlockCommandError, 'message': Message})

    http_request_request = (5, {})
    http_get_request = (5, {})
    http_put_request = (5, {})
    http_patch_request = (5, {})
    http_delete_request = (5, {})
    http_post_request = (5, {})
    http_close_request = (5, {})
    http_recreate_request = (5, {})
    http_email_login_request = (5, {})
    http_static_login_request = (5, {})
    http_logout_request = (5, {})
    http_start_private_message_request = (5, {})
    http_send_message_request = (5, {})
    http_send_typing_request = (5, {})
    http_send_file_request = (5, {})
    http_delete_message_request = (5, {})
    http_delete_messages_request = (5, {})
    http_edit_message_request = (5, {})
    http_get_message_request = (5, {})
    http_logs_from_request = (5, {})
    http_pin_message_request = (5, {})
    http_unpin_message_request = (5, {})
    http_pins_from_request = (5, {})
    http_kick_request = (5, {})
    http_ban_request = (5, {})
    http_unban_request = (5, {})
    http_server_voice_state_request = (5, {})
    http_edit_profile_request = (5, {})
    http_change_my_nickname_request = (5, {})
    http_change_nickname_request = (5, {})
    http_edit_channel_request = (5, {})
    http_create_channel_request = (5, {})
    http_delete_channel_request = (5, {})
    http_leave_server_request = (5, {})
    http_delete_server_request = (5, {})
    http_create_server_request = (5, {})
    http_edit_server_request = (5, {})
    http_get_bans_request = (5, {})
    http_prune_members_request = (5, {})
    http_estimate_pruned_members_request = (5, {})
    http_create_invite_request = (5, {})
    http_get_invite_request = (5, {})
    http_invites_from_request = (5, {})
    http_accept_invite_request = (5, {})
    http_delete_invite_request = (5, {})
    http_edit_role_request = (5, {})
    http_delete_role_request = (5, {})
    http_replace_roles_request = (5, {})
    http_create_role_request = (5, {})
    http_edit_channel_permissions_request = (5, {})
    http_delete_channel_permissions_request = (5, {})
    http_move_member_request = (5, {})
    http_application_info_request = (5, {})
    http_get_gateway_request = (5, {})

    http_request_response = (6, {})
    http_get_response = (6, {})
    http_put_response = (6, {})
    http_patch_response = (6, {})
    http_delete_response = (6, {})
    http_post_response = (6, {})
    http_close_response = (6, {})
    http_recreate_response = (6, {})
    http_email_login_response = (6, {})
    http_static_login_response = (6, {})
    http_logout_response = (6, {})
    http_start_private_message_response = (6, {})
    http_send_message_response = (6, {})
    http_send_typing_response = (6, {})
    http_send_file_response = (6, {})
    http_delete_message_response = (6, {})
    http_delete_messages_response = (6, {})
    http_edit_message_response = (6, {})
    http_get_message_response = (6, {})
    http_logs_from_response = (6, {})
    http_pin_message_response = (6, {})
    http_unpin_message_response = (6, {})
    http_pins_from_response = (6, {})
    http_kick_response = (6, {})
    http_ban_response = (6, {})
    http_unban_response = (6, {})
    http_server_voice_state_response = (6, {})
    http_edit_profile_response = (6, {})
    http_change_my_nickname_response = (6, {})
    http_change_nickname_response = (6, {})
    http_edit_channel_response = (6, {})
    http_create_channel_response = (6, {})
    http_delete_channel_response = (6, {})
    http_leave_server_response = (6, {})
    http_delete_server_response = (6, {})
    http_create_server_response = (6, {})
    http_edit_server_response = (6, {})
    http_get_bans_response = (6, {})
    http_prune_members_response = (6, {})
    http_estimate_pruned_members_response = (6, {})
    http_create_invite_response = (6, {})
    http_get_invite_response = (6, {})
    http_invites_from_response = (6, {})
    http_accept_invite_response = (6, {})
    http_delete_invite_response = (6, {})
    http_edit_role_response = (6, {})
    http_delete_role_response = (6, {})
    http_replace_roles_response = (6, {})
    http_create_role_response = (6, {})
    http_edit_channel_permissions_response = (6, {})
    http_delete_channel_permissions_response = (6, {})
    http_move_member_response = (6, {})
    http_application_info_response = (6, {})
    http_get_gateway_response = (6, {})

    client_event_error = (7, {'event': str, 'args': tuple, 'kwargs': dict})  # Variadic parameters

    start_private_message = (0, {})
    send_message = (0, {})
    send_typing = (0, {})
    send_file = (0, {})
    delete_message = (0, {})
    delete_messages = (0, {})
    purge_from = (0, {})
    edit_message = (0, {})
    get_message = (0, {})
    pin_message = (0, {})
    unpin_message = (0, {})
    pins_from = (0, {})
    request_offline_members = (0, {})
    kick = (0, {})
    ban = (0, {})
    unban = (0, {})
    server_voice_state = (0, {})
    edit_profile = (0, {})
    change_status = (0, {})
    change_nickname = (0, {})
    edit_channel = (0, {})
    move_channel = (0, {})
    create_channel = (0, {})
    delete_channel = (0, {})
    leave_server = (0, {})
    delete_server = (0, {})
    create_server = (0, {})
    edit_server = (0, {})
    get_bans = (0, {})
    prune_members = (0, {})
    estimate_pruned_members = (0, {})
    create_invite = (0, {})
    get_invite = (0, {})
    invites_from = (0, {})
    accept_invite = (0, {})
    delete_invite = (0, {})
    move_role = (0, {})
    edit_role = (0, {})
    delete_role = (0, {})
    add_roles = (0, {})
    remove_roles = (0, {})
    replace_roles = (0, {})
    create_role = (0, {})
    edit_channel_permissions = (0, {})
    delete_channel_permissions = (0, {})
    move_member = (0, {})
    join_voice_channel = (0, {})

    http_request = (8, {})
    http_get = (8, {})
    http_put = (8, {})
    http_patch = (8, {})
    http_delete = (8, {})
    http_post = (8, {})
    http_close = (8, {})
    http_recreate = (8, {})
    http_email_login = (8, {})
    http_static_login = (8, {})
    http_logout = (8, {})
    http_start_private_message = (8, {})
    http_send_message = (8, {})
    http_send_typing = (8, {})
    http_send_file = (8, {})
    http_delete_message = (8, {})
    http_delete_messages = (8, {})
    http_edit_message = (8, {})
    http_get_message = (8, {})
    http_logs_from = (8, {})
    http_pin_message = (8, {})
    http_unpin_message = (8, {})
    http_pins_from = (8, {})
    http_kick = (8, {})
    http_ban = (8, {})
    http_unban = (8, {})
    http_server_voice_state = (8, {})
    http_edit_profile = (8, {})
    http_change_my_nickname = (8, {})
    http_change_nickname = (8, {})
    http_edit_channel = (8, {})
    http_create_channel = (8, {})
    http_delete_channel = (8, {})
    http_leave_server = (8, {})
    http_delete_server = (8, {})
    http_create_server = (8, {})
    http_edit_server = (8, {})
    http_get_bans = (8, {})
    http_prune_members = (8, {})
    http_estimate_pruned_members = (8, {})
    http_create_invite = (8, {})
    http_get_invite = (8, {})
    http_invites_from = (8, {})
    http_accept_invite = (8, {})
    http_delete_invite = (8, {})
    http_edit_role = (8, {})
    http_delete_role = (8, {})
    http_replace_roles = (8, {})
    http_create_role = (8, {})
    http_edit_channel_permissions = (8, {})
    http_delete_channel_permissions = (8, {})
    http_move_member = (8, {})
    http_application_info = (8, {})
    http_get_gateway = (8, {})

    def __str__(self):
        return self.name

    def __call__(self, *args, **kwargs):
        self.emit(*args, **kwargs)

    async def emit(self, *args, client=None, **kwargs):
        client = client or inspect.currentframe().f_back.f_locals['self'].client
        await client.events.emit(self, *args, **kwargs)

    @property
    def type(self):
        return self.value.type

    @property
    def params(self):
        return self.value.params


setattr(EVENT, 'TYPE', EVENTTYPE)
